version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  server:
    build: ./server
    container_name: todo-server
    ports:
      - "8000:8080"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/tododb

  client:
    build: ./client
    container_name: todo-client
    ports:
      - "3000:80"
    depends_on:
      - server

volumes:
  mongo-data:
